### ISSUE TITLE
Support union types

### ISSUE THREAD

**Issue by dannynelson** [dannynelson/json-schema-to-flow-type#3]
A json schema [supports defining union types](https://spacetelescope.github.io/understanding-json-schema/reference/type.html):
```json
{"type": ["string", "number"]}
```

This should convert to a [flow union type](https://flowtype.org/docs/union-intersection-types.html):
```js
string | number
```

**Comment by morlay** [comment]
It already supported. https://github.com/morlay/json-schema-to-flow-type/blob/master/src/FlowSchema.js#L145 

At least for simple schema.

```js
parseSchema({
    id: "Test",
    type: [ "string", "number" ],
});
```
will be 
```js
export type Test = string | number;
```

**Comment by morlay** [comment]
BTW, I am giving up Flow.js and moving to TypeScript. 
`flow-bin` is really slow and `flow-typed` make me crazy.

So I am not sure I can continue maintain this package without focusing Flow.js.
Could you take over this package?

**Comment by dannynelson** [comment]
@morlay ok, I will come up with a more specific test to reproduce.

Yes, my company, [goodeggs](https://github.com/goodeggs), can take over the module.
Can you also add `goodeggs` as an owner of the npm package?

**Comment by morlay** [comment]
Cool，I can't transfer to goodeggs, so to you first.
npm added goodeggs. Thanks ~

**Comment by dannynelson** [comment]
Great, thanks!
